name    'dominickaiser-filepush'
version '0.0.5'
author 'Demi Benson, Dominic Kaiser'
dependency 'puppetlabs/stdlib', '>=3.0.0'
license 'Apache License, Version 2.0'
summary 'A module to push files'
description 'This module is a simple file push from a source to target and creates parent directories if needed. It also was created in mind to work with Foreman so that I could enter parameter values in Foremans new puppet classes area.'
